// <auto-generated />
using CounterPartyImport.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CounterPartyImport.Migrations
{
    [DbContext(typeof(CounterPartyImportDbContext))]
    partial class CounterPartyImportDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CounterPartyImport.Entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ExternalId")
                        .IsRequired();

                    b.Property<string>("Fax")
                        .HasMaxLength(50);

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsForwarder");

                    b.Property<string>("LegalName")
                        .IsRequired();

                    b.Property<string>("Phone")
                        .HasMaxLength(50);

                    b.Property<string>("TradingName")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasName("AlternateKey_ExternalId");

                    b.ToTable("Companies");
                });
#pragma warning restore 612, 618
        }
    }
}
